# Generated by Django 5.0.3 on 2024-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carausel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pics/%y/%m/%d/")),
                ("title", models.CharField(max_length=50)),
                ("sub_title", models.CharField(max_length=100)),
            ],
        ),
    ]
