# Generated by Django 5.0.3 on 2024-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.CharField(
                default="du lịch",
                max_length=100,
                verbose_name=["du lịch", "thức ăn", "công việc", "giải trí"],
            ),
        ),
    ]
