# Generated by Django 5.0.3 on 2024-04-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_post_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.CharField(
                choices=[
                    ("du lịch", "Du lịch"),
                    ("thức ăn", "Thức ăn"),
                    ("công việc", "Công việc"),
                    ("giải trí", "Giải trí"),
                ],
                default="du_lịch",
                max_length=100,
            ),
        ),
    ]
