# Generated by Django 5.0.3 on 2024-04-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="icon",
        ),
    ]
