# Generated by Django 5.0.3 on 2024-04-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_remove_comment_id_comment_comment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentchild",
            name="tag",
            field=models.CharField(default="user", max_length=150),
        ),
    ]
