# Generated by Django 5.0.3 on 2024-04-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_commentchild_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentchild",
            name="tag",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
