# Generated by Django 5.0.3 on 2024-04-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_comment_commentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="commentchild",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
