# Generated by Django 5.0.3 on 2024-05-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_userprofiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofiles",
            name="user",
        ),
    ]
