# Generated by Django 5.0.3 on 2024-05-05 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_remove_userprofiles_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfiles",
            new_name="UserProfile",
        ),
    ]
