# Generated by Django 5.0.3 on 2024-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_alter_userprofiles_age_alter_userprofiles_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofiles",
            name="age",
        ),
        migrations.AddField(
            model_name="userprofiles",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofiles",
            name="day",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userprofiles",
            name="month",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userprofiles",
            name="year",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="userprofiles",
            name="phone_number",
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
