# Generated by Django 5.0.3 on 2024-05-05 07:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_alter_userprofiles_day_alter_userprofiles_month_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfiles",
            new_name="UserProfile",
        ),
    ]
