# Generated by Django 5.0.3 on 2024-05-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0034_alter_userprofile_day_alter_userprofile_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
