# Generated by Django 5.0.3 on 2024-05-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
