# Generated by Django 5.0.3 on 2024-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0036_remove_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                blank=True, default="example@gmail.com", max_length=254
            ),
        ),
    ]
