# Generated by Django 5.0.3 on 2024-05-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0039_alter_userprofile_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="OtherSource",
            field=models.JSONField(max_length=200, null=True),
        ),
    ]
