# Generated by Django 5.0.3 on 2024-05-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0040_post_othersource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="OtherSource",
        ),
        migrations.AddField(
            model_name="post",
            name="citation_url",
            field=models.URLField(null=True),
        ),
    ]
