# Generated by Django 5.0.3 on 2024-05-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0041_remove_post_othersource_post_citation_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="citation_url",
            field=models.URLField(default="", null=True),
        ),
    ]
