# Generated by Django 5.0.3 on 2024-05-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0042_alter_post_citation_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="citation_url",
            field=models.CharField(default="", max_length=200, null=True),
        ),
    ]
