# Generated by Django 5.0.3 on 2024-05-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0043_alter_post_citation_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="commentchild",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
    ]
