# Generated by Django 5.0.3 on 2024-05-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0044_comment_user_id_commentchild_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(null=True, upload_to="comment/images"),
        ),
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(blank=True, default="user", max_length=50),
        ),
        migrations.AddField(
            model_name="commentchild",
            name="image",
            field=models.ImageField(null=True, upload_to="comment/images"),
        ),
        migrations.AddField(
            model_name="commentchild",
            name="username",
            field=models.CharField(blank=True, default="user", max_length=50),
        ),
    ]
