# Generated by Django 5.0.3 on 2024-05-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0045_comment_image_comment_username_commentchild_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="father",
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                default="/static/images/user-icon.png",
                null=True,
                upload_to="comment/images",
            ),
        ),
        migrations.AlterField(
            model_name="commentchild",
            name="image",
            field=models.ImageField(
                default="/static/images/user-icon.png",
                null=True,
                upload_to="comment/images",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="defaultName",
            field=models.CharField(blank=True, default="User", max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="/static/images/user-icon.png", upload_to="profiles/images"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="year",
            field=models.IntegerField(default=2010),
        ),
    ]
