# Generated by Django 5.0.3 on 2024-05-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0046_remove_comment_father_alter_comment_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="comment",
            name="topic_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="commentchild",
            name="comment_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="commentchild",
            name="topic_id",
            field=models.IntegerField(default=1),
        ),
    ]
