# Generated by Django 5.0.3 on 2024-05-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0047_alter_comment_comment_content_alter_comment_topic_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="commentchild",
            name="author",
        ),
    ]
