# Generated by Django 5.0.3 on 2024-05-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0049_alter_comment_image_alter_commentchild_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                default="static/images/user-icon.png", upload_to="comment/images"
            ),
        ),
        migrations.AlterField(
            model_name="commentchild",
            name="image",
            field=models.ImageField(
                default="static/images/user-icon.png", upload_to="comment/images"
            ),
        ),
    ]
