# Generated by Django 5.0.3 on 2024-05-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0057_remove_userprofile_user_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
    ]
