# Generated by Django 5.0.3 on 2024-05-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0062_alter_notification_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="user_id",
            field=models.IntegerField(unique=True),
        ),
    ]
