# Generated by Django 5.0.3 on 2024-05-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0064_remove_notification_user_id_notification_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                default="/static/images/user-icon.png", upload_to="profiles/images"
            ),
        ),
    ]
