# Generated by Django 5.0.3 on 2024-05-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0068_alter_post_author_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
