# Generated by Django 5.0.3 on 2024-05-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0069_remove_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="link",
            new_name="to",
        ),
    ]
