# Generated by Django 5.0.3 on 2024-05-21 01:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0070_rename_link_notification_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification",
            new_name="UserNotification",
        ),
    ]
