# Generated by Django 5.0.3 on 2024-05-21 02:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0071_rename_notification_usernotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserNotification",
            new_name="Notification",
        ),
    ]
