# Generated by Django 5.0.3 on 2024-05-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0072_rename_usernotification_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.AddField(
            model_name="notification",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
    ]
