# Generated by Django 5.0.3 on 2024-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0073_remove_notification_user_notification_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
    ]
