# Generated by Django 5.0.3 on 2024-05-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0074_notification_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="username",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
