# Generated by Django 5.0.3 on 2024-05-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0075_alter_notification_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="dislike",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="commentchild",
            name="dislike",
            field=models.IntegerField(default=0),
        ),
    ]
